dataset: 'rover'

mapping:
  Calibration:
    depth_scale: 1000.0

tracking:
  buffer: 3000
  warmup: 12
  multiview_filter:
    visible_num: 2  
  frontend:
    keyframe_thresh: 3.0
    radius: 2
  backend:
    loop_nms: 10
    BA_type: "DBA"
    normalize: False

cam:  #NOTE: intrinsic is different per scene in TUM
  # refer to https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats#intrinsic_camera_calibration_of_the_kinect
  png_depth_scale: 1000.0 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 8
  W_edge: 8
  H_out: 384
  W_out: 512

data:
  dataset_root: datasets/ROVER
  output: output/ROVER